steps:
  - id: "Executando testes unitários"
    name: "gcr.io/cloud-builders/go"
    args: [ "go", "run", "golang_image", "go", "test"]

  - id: "Testanto a build da aplicação"
    name: "gcr.io/cloud-builders/go"
    args: 
      - go
      - build
