steps:

  - id: "Executando testes unitários"
    name: "gcr.io/cloud-builders/go"
    args: ["test"] 

  - id: "Compilando aplicação e executando"
    name: "gcr.io/cloud-builders/docker"
    args:
      - build
      - "*.go"
      - "&&"
      - ./hello
