steps:
  - id: "Fazendo build da imagem"
    name: "gcr.io/cloud-builders/docker"
    args: 
      - build
      - -t 
      - golang_image
      - -f 
      - Dockerfile
      - .

  - id: "Executando testes unitários"
    name: "gcr.io/cloud-builders/docker"
    args: [ "docker", "run", "golang_image", "go", "test"]

  - id: "Testanto a build da aplicação"
    name: "gcr.io/cloud-builders/docker"
    args: 
      - run
      - golang_image
      - go
      - build
