
# BUILDER IMAGE
FROM golang:1.13.12-alpine3.12 as builder

WORKDIR /go/src

# compile go scripts
COPY . /go/src

RUN export GOPATH=/go/src
RUN export GOROOT=/go/src
RUN apk add git
RUN go get github.com/gorilla/mux
# RUN go install
RUN go build -o hello *.go

# FINAL IMAGE
FROM golang:1.13.12-alpine3.12

WORKDIR /go/src
COPY --from=builder /go/src/hello ./hello

RUN apk add bash
